#!/usr/bin/env bash
# T3-Snow: merge the latest official T3 Code (pingdotgg/t3code main) into the
# current branch.
#
# Resolves the conflicts every sync produces on its own:
#   - .github/workflows: take upstream's file, then re-add the fork guard
#   - pnpm-lock.yaml:    take upstream's lockfile, then re-resolve ours on top
#   - routeTree.gen.ts:  regenerated by building the web app
# Anything else is left for a person; the script stops with the merge in
# progress and lists the files.
#
# Usage: scripts/snow/sync-upstream.sh
set -euo pipefail

UPSTREAM_URL="https://github.com/pingdotgg/t3code.git"
cd "$(git rev-parse --show-toplevel)"

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Commit or stash your changes before syncing." >&2
  exit 1
fi

if ! git remote get-url upstream >/dev/null 2>&1; then
  git remote add upstream "$UPSTREAM_URL"
fi
git fetch --no-tags upstream main

if git merge-base --is-ancestor upstream/main HEAD; then
  echo "Already up to date with upstream."
  exit 0
fi

upstream_sha="$(git rev-parse --short upstream/main)"
if git merge --no-edit --no-ff -m "Sync upstream T3 Code (${upstream_sha})" upstream/main; then
  merged_cleanly=true
else
  merged_cleanly=false
fi

regenerate_routes=false
if [[ "$merged_cleanly" == false ]]; then
  while IFS= read -r file; do
    case "$file" in
      .github/workflows/snow-*)
        git checkout --ours -- "$file" && git add -- "$file"
        ;;
      .github/workflows/*)
        if git cat-file -e "upstream/main:$file" 2>/dev/null; then
          git checkout --theirs -- "$file" && git add -- "$file"
        else
          git rm -q -- "$file"
        fi
        ;;
      pnpm-lock.yaml)
        git checkout --theirs -- "$file"
        ;;
      apps/web/src/routeTree.gen.ts)
        git checkout --theirs -- "$file"
        regenerate_routes=true
        ;;
    esac
  done < <(git diff --name-only --diff-filter=U)

  remaining="$(git diff --name-only --diff-filter=U | grep -v -e '^pnpm-lock.yaml$' -e '^apps/web/src/routeTree.gen.ts$' || true)"
  if [[ -n "$remaining" ]]; then
    echo "These files need a manual merge (the merge is still in progress):" >&2
    echo "$remaining" >&2
    echo "Resolve them, then run this script's remaining steps: vp install, commit." >&2
    exit 2
  fi
fi

node scripts/snow/guard-upstream-workflows.ts
git add .github/workflows

# Auto-merged lockfiles can be inconsistent, so always re-resolve.
vp install --lockfile-only
git add pnpm-lock.yaml

if [[ "$regenerate_routes" == true ]]; then
  vp install
  vp run --filter @t3tools/web build
  git add apps/web/src/routeTree.gen.ts
fi

if [[ "$merged_cleanly" == false ]] || ! git diff --cached --quiet; then
  if git rev-parse -q --verify MERGE_HEAD >/dev/null; then
    git commit --no-edit
  else
    git commit -m "Keep upstream workflows guarded after sync"
  fi
fi

echo "Merged upstream ${upstream_sha}."
